[package]
name = "compute-waster"
version = "0.1.0"
authors = ["Paul Le Grand des Cloizeaux <paul.legranddescloizeaux@datadoghq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
